apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sync-layer-server
  description: Service that continuously synchronizes geospatial layer data from a third-party GraphQL API into a remote PostgreSQL database
  annotations:
    github.com/project-slug: MapColonies/sync-layer-server
  tags:
    - nodejs
    - typescript
    - expressjs
    - yahalom
spec:
  type: service
  lifecycle: production
  owner: 3D
  system: yahalom
