apiVersion: v2
name: sync-layer-server
description: >-
  Helm chart for the sync-layer-server service, which synchronizes geospatial
  layers from the third-party API into PostgreSQL
type: application
version: 1.2.0
appVersion: 1.2.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
